#!/usr/bin/env bash
# hooks/escalate.sh
# on_error: logs errors to memory/errors.md and notifies developer
set -e

ERROR_LOG="${ERROR_LOG_PATH:-memory/errors.md}"
NOTIFY_DEVELOPER="${NOTIFY_DEVELOPER:-true}"
ERROR_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Inputs from gitclaw runtime
ERROR_MESSAGE="${DEVMIND_ERROR_MESSAGE:-Unknown error}"
ERROR_SKILL="${DEVMIND_ERROR_SKILL:-unknown skill}"
ERROR_CONTEXT="${DEVMIND_ERROR_CONTEXT:-No additional context}"
ERROR_CODE="${DEVMIND_ERROR_CODE:-1}"

# Ensure directory exists
mkdir -p "$(dirname "$ERROR_LOG")"

# Initialize errors.md if it doesn't exist
if [ ! -f "$ERROR_LOG" ]; then
  cat > "$ERROR_LOG" << 'EOF'
# devmind Error Log
> Auto-generated by devmind escalate hook.
> Review these errors to understand where devmind encountered problems.

EOF
fi

# Append structured error entry
cat >> "$ERROR_LOG" << EOF
## Error — $ERROR_DATE
- **Skill:** $ERROR_SKILL
- **Error Code:** $ERROR_CODE
- **Message:** $ERROR_MESSAGE
- **Context:** $ERROR_CONTEXT

EOF

echo "[devmind escalate] Error logged to $ERROR_LOG"

# Notify developer in session output
if [ "$NOTIFY_DEVELOPER" = "true" ]; then
  echo ""
  echo "⚠️  devmind encountered an error in skill: $ERROR_SKILL"
  echo "    $ERROR_MESSAGE"
  echo "    Full details logged to: $ERROR_LOG"
  echo ""
  echo "    To continue: fix the issue and re-invoke the skill."
  echo "    To review all errors: read $ERROR_LOG"
fi

exit 0  # Escalate hook should not itself fail and cause a loop
